[package]
name = "booksignatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
human-panic = "1.1.5"
lopdf = "0.31.0"
regex = "1.8.4"
